version: '3.1'

services:
    nagios:
        build:
            context: ../nagios
            args:
                TZ: "America/New_York"
        image: nagios:20170916
        container_name: nagios
        hostname: nagios
#        restart: unless-stopped
        environment:
            TZ: "America/New_York"
        volumes:
            - ../nagios/conf:/conf.d
        ports:
            - 8003:80
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
