version: '3.5'

services:
    nagios:
        build:
            args:
                CONTAINER_NAME: nagios
                CONTAINER_VERSION: 1.0.6
                DEBUG_TRACE: 0
                DBUSER: ${CFG_MYSQL_USER}
                DBPASS: ${CFG_MYSQL_PASSWORD}
                DBHOST: mysql
                DBNAME: nconf
                FROM_BASE: base_container:20180314
            cache_from:
                - base_container:20180314
                - alpine:3.6                 
            context: . 
            dockerfile: Dockerfile
        container_name: nagios
        environment:
            DBHOST: 172.18.0.5
            DBNAME: nconf
            DBUSER: ${CFG_MYSQL_USER}
            DBPASS: ${CFG_MYSQL_PASSWORD}
        hostname: nagios
        image: nagios:20180314
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 25:25
            - 8003:80
#        restart: unless-stopped
        volumes:
            - ./vols/archives:/usr/local/nagios/var/archives
            - ./vols/rrd:/usr/local/nagios/var/rrd
            - ./vols/config:/usr/local/nagios/share/nconf/output
            - ./vols/log:/var/log
