version: '3.3'

services:
    nagios:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: nagios
                CONTAINER_VERSION: ${CONTAINER_VERSION:-3.0.0}
                FROM_BASE: ${DOCKER_REGISTRY:-}php5:${CONTAINER_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}base_container:${CONTAINER_TAG:-latest}
                - ${DOCKER_REGISTRY:-}supervisord:${CONTAINER_TAG:-latest}
                - ${DOCKER_REGISTRY:-}php5:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: nagios
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            NAGIOS_GITHUB_CREDENTIALS: ${CFG_GITHUB_USER}:${CFG_GITHUB_TOKEN}
            NAGIOS_GITHUB_EMAIL: $CFG_GITHUB_EMAIL
            NAGIOS_GITHUB_NAME: $CFG_GITHUB_NAME
            NAGIOS_PASS: $CFG_PASS
            NAGIOS_USER: $CFG_USER
            NCONF_DBHOST: mysql
            NCONF_DBNAME: nconf
            NCONF_DBPASS: $CFG_PASS
            NCONF_DBUSER: $CFG_USER
            SUPERVISORD_PASS: $CFG_PASS         
            SUPERVISORD_USER: $CFG_USER
        hostname: nagios
        image: ${DOCKER_REGISTRY:-}nagios:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 25:25
            - 8003:80
#        restart: unless-stopped
        user: '1000'
        volumes:
            - ./vols/archives:/usr/local/nagios/var/archives
            - ./vols/rrd:/usr/local/nagios/var/rrd
            - ./vols/config:/usr/local/nagios/share/nconf/output
            - ./vols/log:/var/log
