version: '3.1'

services:
    nagios:
        build:
            context: ../nagios
            args:
                TZ: "America/New_York"
        image: nagios:20171019
        container_name: nagios
        hostname: nagios
#        restart: unless-stopped
        environment:
            TZ: "America/New_York"
            DBHOST: "mysql"
            DBNAME: "nconf"
            DBUSER: "bobb"
            DBPASS: "123Oleary" 
        volumes:
            - ../nagios/conf/nconf/output:/usr/local/nagios/share/nconf/output
            - ../nagios/log:/var/log
        ports:
            - 25:25
            - 8003:80
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
