version: '3.1'

services:
    nagios:
        build:
            context: ../nagios
            args:
                TZ: "America/New_York"
        image: nagios:20171019
        container_name: nagios
        hostname: nagios
#        restart: unless-stopped
        environment:
            TZ: "America/New_York"
        volumes:
            - ../nagios/etc/myconf:/etc/myconf
            - ../nagios/etc/myconf/nginx.conf:/etc/nginx/nginx.conf
            - ../nagios/etc/myconf/conf.d:/etc/nginx/conf.d
            - ../nagios/etc/supervisor.d:/etc/supervisor.d
            - ../nagios/conf/nconf/config:/usr/local/nagios/share/nconf/config
            - ../nagios/conf/nconf/ADD-ONS:/usr/local/nagios/share/nconf/ADD-ONS
            - ../nagios/conf/nconf/output:/usr/local/nagios/share/nconf/output
            - ../nagios/log:/var/log
        ports:
            - 8003:80
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
