version: '3.1'

services:
    nagios:
        build:
            context: ../nagios
            args:
                TZ: "America/New_York"
        image: nagios:20171219
        container_name: nagios
        hostname: nagios
        restart: unless-stopped
        environment:
            TZ: "America/New_York"
            DBHOST: "172.18.0.5"
            DBNAME: "nconf"
            DBUSER: ${CFG_MYSQL_USER}
            DBPASS: ${CFG_MYSQL_PASSWORD}
        links:
            - mysql
        volumes:
            - ../nagios/vols/archives:/usr/local/nagios/var/archives
            - ../nagios/vols/rrd:/usr/local/nagios/var/rrd
            - ../nagios/vols/config:/usr/local/nagios/share/nconf/output
            - ../nagios/vols/log:/var/log
        ports:
            - 25:25
            - 8003:80
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
